
export default async function getStations(){
    const stations = [
        "Palmeiras-Barra Funda",
        "Marechal Deodoro",
        "Santa Cecília",
        "República",
        "Sé",
        "Anhangabaú",
        "Pedro II",
        "Brás",
        "Bresser-Mooca",
        "Belém",
        "Tatuapé",
        "Carrão",
        "Penha",
        "Vila Matilde",
        "Guilhermina-Esperança",
        "Patriarca",
        "Artur Alvim",
        "Corinthians-Itaquera",
        "Butantã",
        "Pinheiros",
        "Faria Lima",
        "Fradique Coutinho",
        "Paulista",
        "Higienópolis-Mackenzie",
        "Republíca",
        "Luz",
        "São Bento",
        "Tiradentes",
        "Armênia",
        "Portuguesa-Tietê",
        "Carandiru",
        "Santana",
        "Jardim São Paulo-Ayrton Senna",
        "Parada Inglesa",
        "Tucuruvi",
        "Vila Prudente",
        "Tamanduateí",
        "Sacomã",
        "Alto do Ipiranga",
        "Santos-Imigrantes",
        "Chácara Klabin",
        "Ana Rosa",
        "Paraíso",
        "Brigadeiro",
        "Trianon-Masp",
        "Consolação",
        "Clínicas",
        "Santana-Imigrantes",
        "Vila Mariana",
        "Santa Cruz",
        "Praça da Árvore",
        "Saúde",
        "São Judas",
        "Conceição",
        "Jabaquara"
    ]

    return stations
}